#!/usr/bin/env python3
"""Add (or refresh) Obsidian wikilink 'shadow' blocks to every .kb/ doc.

WHY: the KB uses OKF bundle-absolute markdown links `](/.kb/x/y.md)`. Obsidian's graph is
built from wikilinks `[[...]]`, and it can't follow the leading-slash absolute form. This
appends a clearly-delimited block of path-qualified wikilinks mirroring each doc's existing
outbound /.kb/ links, so the Obsidian graph edges light up — WITHOUT changing the canonical
markdown links (OKF conformance stays intact).

Vault assumption: WHOLE REPO is the vault, so wikilink targets are repo-root-relative paths
(e.g. [[.kb/fleet/4736-105|4736-105]]) to disambiguate the 46 train-number basename collisions
between .kb/fleet/ and .kb/assets/.

Idempotent: the block is fenced by markers and fully regenerated each run. Reversible: delete
everything from the START marker to EOF to strip it.
"""
import glob, re, os

START = "<!-- OBSIDIAN-GRAPH-LINKS (auto-generated by scripts/add_obsidian_shadows.py — safe to delete) -->"
LINK_RE = re.compile(r'\]\((/\.kb/[^)#]+\.md)')

def wikilink(target_abs):
    # target_abs like "/.kb/topics/foo.md" -> repo-relative ".kb/topics/foo" + display "foo"
    rel = target_abs.lstrip("/")            # .kb/topics/foo.md
    noext = rel[:-3]                         # .kb/topics/foo
    display = os.path.basename(noext)        # foo
    return f"[[{noext}|{display}]]"

def main():
    changed = 0
    for f in sorted(glob.glob(".kb/**/*.md", recursive=True)):
        txt = open(f, encoding="utf-8").read()
        # strip any prior block
        base = txt.split("\n" + START)[0].rstrip()
        # collect unique outbound /.kb/ links, excluding self
        self_abs = "/" + f.replace(os.sep, "/")
        targets = []
        seen = set()
        for m in LINK_RE.finditer(base):
            t = m.group(1)
            if t == self_abs or t in seen:
                continue
            # only shadow links whose target actually exists
            if os.path.exists("." + t):
                seen.add(t); targets.append(t)
        if not targets:
            # still normalise (remove stale block if base had none now)
            new = base + "\n"
            if new != txt:
                open(f, "w", encoding="utf-8").write(new); changed += 1
            continue
        block = [ "", START,
                  "> Obsidian graph edges (mirror of the Related/inline links above). "
                  "The canonical links are the markdown `](/.kb/…)` ones; these `[[…]]` exist only "
                  "so Obsidian's graph view connects the nodes.", "" ]
        block += [f"- {wikilink(t)}" for t in targets]
        new = base + "\n" + "\n".join(block) + "\n"
        if new != txt:
            open(f, "w", encoding="utf-8").write(new); changed += 1
    print(f"updated {changed} files with Obsidian wikilink shadows")

if __name__ == "__main__":
    main()
