UserParameter=check_poe_worst,/usr/local/bin/check-poe.sh worst
UserParameter=check_poe_fail_count,/usr/local/bin/check-poe.sh count_poe_fail
UserParameter=check_poe_linkdown_count,/usr/local/bin/check-poe.sh count_link_down
